
name: feature_pipeline

networks:
  redpanda_network:
    name: redpanda_network
    driver: bridge

services:
  trade-producer:
    container_name: trade-producer
    build:
      context: ../services/trade-producer
    
    networks:
      - redpanda_network
    environment:
      KAFKA_BROKER_ADDRESS: redpanda-0:9092

  trade-to-ohlc: 
    container_name: ohlc
    build:
      context: ../services/trade-to-ohlc
    networks:
      - redpanda_network
    environment:
      KAFKA_BROKER_ADDRESS: redpanda-0:9092
      OHLC_WINDOW_SECONDS: 60

    
  kafka-to-feature:
    container_name: kafka-to-store
    build:
      context: ../services/kafka-to-store
    networks:
      - redpanda_network
    environment:
      KAFKA_BROKER_ADDRESS: redpanda-0:9092
    env_file:
      - ../services/kafka-to-store/.env